// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCiOaMjito_tXLi033vDQZLSti3vnQU18',
    appId: '1:389414759725:web:4c0f789e6b88422a58f7a4',
    messagingSenderId: '389414759725',
    projectId: 'fypproject-cf2ac',
    authDomain: 'fypproject-cf2ac.firebaseapp.com',
    storageBucket: 'fypproject-cf2ac.appspot.com',
    measurementId: 'G-N3N8ZBJFHX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0fRPPaFgnhfTzDvLXZyz9xxes71razNg',
    appId: '1:389414759725:android:378e992af13851a758f7a4',
    messagingSenderId: '389414759725',
    projectId: 'fypproject-cf2ac',
    storageBucket: 'fypproject-cf2ac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEPz2lK3jiIzXG9q3qojbVnDBu5SBwx4g',
    appId: '1:389414759725:ios:eff4c601955ae4e358f7a4',
    messagingSenderId: '389414759725',
    projectId: 'fypproject-cf2ac',
    storageBucket: 'fypproject-cf2ac.appspot.com',
    iosBundleId: 'com.example.mentorapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEPz2lK3jiIzXG9q3qojbVnDBu5SBwx4g',
    appId: '1:389414759725:ios:58225a364a5bb22e58f7a4',
    messagingSenderId: '389414759725',
    projectId: 'fypproject-cf2ac',
    storageBucket: 'fypproject-cf2ac.appspot.com',
    iosBundleId: 'com.example.mentorapp.RunnerTests',
  );
}
